# https://yarnpkg.com/getting-started/migration#troubleshooting
packageExtensions:
  "@mdi/react@*":
    dependencies:
      "@types/react": "*"
      "eslint-import-resolver-node": "*"
      "react": "*"
  "@pkgr/utils@*":
    dependencies:
      "eslint-import-resolver-node": "*"
      "react": "*"
  "@testing-library/dom@*":
    dependencies:
      "eslint-import-resolver-node": "*"
  "@testing-library/react@*":
    dependencies:
      "eslint-import-resolver-node": "*"
  "@testing-library/user-event@*":
    dependencies:
      "eslint-import-resolver-node": "*"
  "@types/color@*":
    dependencies:
      "color-convert": "*"
  "@types/color-convert@*":
    dependencies:
      "color-name": "*"
  "@types/lodash-es@*":
    dependencies:
      "lodash": "*"
  "@types/jsdom@*":
    dependencies:
      "tough-cookie": "*"
  "@types/react@*":
    dependencies:
      "prop-types": "*"
      "scheduler": "*"
  "@types/react-dom@*":
    dependencies:
      "react": "*"
  "@vanilla-extract/css@*":
    dependencies:
      "eslint-import-resolver-node": "*"
  "constate@*":
    dependencies:
      "eslint-import-resolver-node": "*"
  "debug@*":
    dependencies:
      "supports-color": "*"
  # https://github.com/vercel/next.js/issues/38939
  "eslint-config-next@*":
    dependencies:
      "next": "*"
  "eslint-module-utils@*":
    dependencies:
      "eslint-import-resolver-node": "*"
  "lodash-es@*":
    dependencies:
      "eslint-import-resolver-node": "*"
  "recoil@*":
    dependencies:
      "eslint-import-resolver-node": "*"
  "uuid@*":
    dependencies:
      "eslint-import-resolver-node": "*"
  "vite@*":
    dependencies:
      "supports-color": "*"
  "vitest@*":
    dependencies:
      "eslint-import-resolver-node": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

# https://github.com/vitest-dev/vitest/issues/899
pnpMode: "loose"

yarnPath: .yarn/releases/yarn-3.3.0.cjs
