# https://yarnpkg.com/getting-started/migration#troubleshooting
packageExtensions:
  "debug@*":
    dependencies:
      "supports-color": "*"
  # https://github.com/vercel/next.js/issues/38939
  "eslint-config-next@*":
    dependencies:
      "next": "*"
  "vite@*":
    dependencies:
      "supports-color": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

# https://github.com/vitest-dev/vitest/issues/899
pnpMode: "loose"

yarnPath: .yarn/releases/yarn-3.3.0.cjs
